ocr_config:
  model: vietocr
  pretrained_cnn_model: vgg_transformer
  device: cuda

corner_config:
  model: src/models/corner_detector_v2.1.pt

front_field_config:
  model: src/models/field_detector_v2.pt

back_field_config:
  model: src/models/back_field_model.pt
